-- MySQL Script generated by MySQL Workbench
-- Mon Aug 30 23:23:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Mongkolthorn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Mongkolthorn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mongkolthorn` DEFAULT CHARACTER SET utf8 ;
USE `Mongkolthorn` ;

-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Account` (
  `ACCOUNTID` INT NOT NULL,
  `FNAME` VARCHAR(45) NOT NULL,
  `LNAME` VARCHAR(45) NOT NULL,
  `PHONE` VARCHAR(10) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ACCOUNTID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Product` (
  `PRODUCTID` INT NOT NULL,
  `PNAME` VARCHAR(45) NOT NULL,
  `IMAGE` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(200) NOT NULL,
  `STYLE` CHAR(1) NOT NULL,
  `CATEGORY` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCTID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`SetSize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`SetSize` (
  `SIZEID` INT NOT NULL,
  `Proportion` DECIMAL(6,2) NOT NULL,
  `PRODUCTID` INT NOT NULL,
  PRIMARY KEY (`SIZEID`),
  INDEX `fk_SetSize_Product1_idx` (`PRODUCTID` ASC) VISIBLE,
  CONSTRAINT `fk_SetSize_Product1`
    FOREIGN KEY (`PRODUCTID`)
    REFERENCES `Mongkolthorn`.`Product` (`PRODUCTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Closet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Closet` (
  `ClosetID` INT NOT NULL,
  `PNAME` VARCHAR(45) NOT NULL,
  `IMAGE` VARCHAR(45) NOT NULL,
  `STYLE` CHAR(1) NOT NULL,
  `CATEGORY` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `PickUpDate` DATE NOT NULL,
  PRIMARY KEY (`ClosetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`SaveSize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`SaveSize` (
  `SaveSizeID` INT NOT NULL,
  `Proportion` DECIMAL(6,2) NULL,
  `ACCOUNTID` INT NOT NULL,
  PRIMARY KEY (`SaveSizeID`),
  INDEX `fk_SaveSize_Account1_idx` (`ACCOUNTID` ASC) VISIBLE,
  CONSTRAINT `fk_SaveSize_Account1`
    FOREIGN KEY (`ACCOUNTID`)
    REFERENCES `Mongkolthorn`.`Account` (`ACCOUNTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Colors` (
  `COLORID` INT NOT NULL,
  `COLORNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COLORID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Product_has_Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Product_has_Colors` (
  `HasColorsID` INT NOT NULL,
  `PRODUCTID` INT NOT NULL,
  `COLORID` INT NOT NULL,
  PRIMARY KEY (`HasColorsID`),
  INDEX `fk_Product_has_Colors_Colors1_idx` (`COLORID` ASC) VISIBLE,
  INDEX `fk_Product_has_Colors_Product_idx` (`PRODUCTID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Colors_Product`
    FOREIGN KEY (`PRODUCTID`)
    REFERENCES `Mongkolthorn`.`Product` (`PRODUCTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Colors_Colors1`
    FOREIGN KEY (`COLORID`)
    REFERENCES `Mongkolthorn`.`Colors` (`COLORID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Account_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Account_has_Product` (
  `has_Product` VARCHAR(45) NOT NULL,
  `Account_ACCOUNTID` INT NOT NULL,
  `Product_PRODUCTID` INT NOT NULL,
  `ClosetID` INT NOT NULL,
  PRIMARY KEY (`has_Product`, `ClosetID`),
  INDEX `fk_Account_has_Product_Product1_idx` (`Product_PRODUCTID` ASC) VISIBLE,
  INDEX `fk_Account_has_Product_Account1_idx` (`Account_ACCOUNTID` ASC) VISIBLE,
  INDEX `fk_Account_has_Product_Closet1_idx` (`ClosetID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_has_Product_Account1`
    FOREIGN KEY (`Account_ACCOUNTID`)
    REFERENCES `Mongkolthorn`.`Account` (`ACCOUNTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_has_Product_Product1`
    FOREIGN KEY (`Product_PRODUCTID`)
    REFERENCES `Mongkolthorn`.`Product` (`PRODUCTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_has_Product_Closet1`
    FOREIGN KEY (`ClosetID`)
    REFERENCES `Mongkolthorn`.`Closet` (`ClosetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`AdAccess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`AdAccess` (
  `AAID` INT NOT NULL,
  `UserFNAME` VARCHAR(45) NULL,
  `UserLNAME` VARCHAR(45) NULL,
  `UserPhone` VARCHAR(10) NULL,
  `ClosetID` INT NOT NULL,
  PRIMARY KEY (`AAID`),
  INDEX `fk_AdAccess_Closet1_idx` (`ClosetID` ASC) VISIBLE,
  CONSTRAINT `fk_AdAccess_Closet1`
    FOREIGN KEY (`ClosetID`)
    REFERENCES `Mongkolthorn`.`Closet` (`ClosetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mongkolthorn`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mongkolthorn`.`Admin` (
  `AdminID` INT NOT NULL,
  `AdFNAME` VARCHAR(45) NOT NULL,
  `AdLNAME` VARCHAR(45) NOT NULL,
  `AdEMAIL` VARCHAR(45) NOT NULL,
  `AdPassword` VARCHAR(45) NOT NULL,
  `AAID` INT NOT NULL,
  PRIMARY KEY (`AdminID`),
  INDEX `fk_Admin_AdAccess1_idx` (`AAID` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_AdAccess1`
    FOREIGN KEY (`AAID`)
    REFERENCES `Mongkolthorn`.`AdAccess` (`AAID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
